name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  # Riippuvuuksien asennus ja testien suorittaminen
  test:
    runs-on: ubuntu-latest
    steps:
      # Vaihe 1: Tarkista koodi
      - name: Check out code
        uses: actions/checkout@v4

      # Vaihe 2: Määritä Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Vaihe 3: Asenna riippuvuudet
      - name: Install dependencies
        run: npm install

      # Vaihe 4: Suorita testit
      - name: Run tests
        run: npm test

  # Työ frontend-sovelluksen rakentamiseen
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      # Tallenna koontiartefakti välimuistiin käyttöönottoa varten
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  # GitHub-sivuilla tai muussa käyttöönottokohteessa julkaistava työ
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      # Esimerkki käyttöönotosta GitHub-sivuille (säädä käyttöönottotavoitteen mukaan)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_CUSTOM_TOKEN }}
          publish_dir: build/
